name: Build pull-request

permissions: {}

on:
  pull_request:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-pullrequest:
    name: Build pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: 25
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test build website
        run: yarn build

      - name: Jampack
        run: npx @divriots/jampack build
