name: Build pull-request

permissions: {}

on:
  pull_request:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build-pullrequest:
    name: Build pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 25
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test build website
        run: yarn build

      - name: Jampack
        run: npx @divriots/jampack build
